# Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

1) Créer une liste Python stockant ces températures;

In [1]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperatures_liste)

[24.5, 25.1, 26.3, 27.0, 25.8]


2) Créer un tableau NumPy équivalent stockant ces températures

In [3]:
import numpy as np

temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_array)

[24.5 25.1 26.3 27.  25.8]


3) Effectuer une multiplication par 2 sur ces deux collections

In [5]:
# Sur la liste Python
temperatures_liste_x2 = temperatures_liste * 2
print(temperatures_liste_x2)

print("----------------")

# Sur le tableau NumPy
temperatures_array_x2 = temperatures_array * 2
print(temperatures_array_x2)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
----------------
[49.  50.2 52.6 54.  51.6]


4) Quelle différence observe-t-on ?

Sur la liste python lorsqu'on effectue une multiplication, les elements de la liste se duplique et quand on fait une multiplication sur le tableau numpy on obtient une multiplication element par element

Partie 2 – Création des données

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [6]:
#  Tableau de 10 capteurs, initialement à zéro
temperatures_capteurs = np.zeros(10)
print(temperatures_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Créer un tableau contenant 10 valeurs égales à 1.

In [7]:
# Tableau de 10 valeurs égales à 1
temperatures_uns = np.ones(10)
print(temperatures_uns)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Créer un tableau de 10 valeurs initialisées à 25.

In [8]:
# Tableau de 10 valeurs initialisées à 25
temperatures_25 = np.full(10, 25)
print(temperatures_25)

[25 25 25 25 25 25 25 25 25 25]


4) Créer une matrice identité de taille 5 × 5.

In [9]:
#  Matrice identité 5x5
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [10]:
# Les 24 heures de la journée (0 à 23)
heures = np.arange(24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [11]:
# 10 valeurs régulièrement réparties entre 20°C et 30°C
temperatures_reparties = np.linspace(20, 30, 10)
print(temperatures_reparties)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [12]:
# 100 mesures aléatoires de température, reproductibles
np.random.seed(42)
temperatures_100 = np.random.uniform(20, 30, 100)
print(temperatures_100)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30

# Partie 3 – Exploration des tableaux

1) Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [13]:
# 24 températures d'une journée (aléatoire)
np.random.seed(42)
temperatures_jour = np.random.uniform(20, 30, 24)
print(temperatures_jour)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]


2) Déterminer les propriétés suivantes du tableau
    a) nombre de dimensions 
    b) nombre de valeurs 
    c) type des données 
    d) forme du tableau

In [14]:
# 2) Propriétés du tableau
print("a) Nombre de dimensions :", temperatures_jour.ndim)
print("b) Nombre de valeurs :", temperatures_jour.size)
print("c) Type des données :", temperatures_jour.dtype)
print("d) Forme du tableau :", temperatures_jour.shape)

a) Nombre de dimensions : 1
b) Nombre de valeurs : 24
c) Type des données : float64
d) Forme du tableau : (24,)


# Partie 4 – Indexation et slicing

Considérant le tableau représentant les 24 températures d'une journée, afficher :


In [15]:
# 1) La première mesure
print(temperatures_jour[0])

23.745401188473625


In [16]:
# 2) La dernière mesure
print(temperatures_jour[-1])

23.663618432936918


In [17]:
# 3) La température de 8h
print(temperatures_jour[8])

26.011150117432088


In [18]:
# 4) Les températures de 8h à 12h
print(temperatures_jour[8:13])

[26.01115012 27.08072578 20.20584494 29.69909852 28.32442641]


In [19]:
# 5) Les températures des 6 premières heures
print(temperatures_jour[:6])

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452 ]


In [20]:
# 6) Les températures des heures paires
print(temperatures_jour[::2])

[23.74540119 27.31993942 21.5601864  20.58083612 26.01115012 20.20584494
 28.32442641 21.81824967 23.04242243 24.31945019 26.11852895 22.92144649]
