# Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

1) Créer une liste Python stockant ces températures;

In [1]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperatures_liste)

[24.5, 25.1, 26.3, 27.0, 25.8]


2) Créer un tableau NumPy équivalent stockant ces températures

In [3]:
import numpy as np

temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_array)

[24.5 25.1 26.3 27.  25.8]


3) Effectuer une multiplication par 2 sur ces deux collections

In [5]:
# Sur la liste Python
temperatures_liste_x2 = temperatures_liste * 2
print(temperatures_liste_x2)

print("----------------")

# Sur le tableau NumPy
temperatures_array_x2 = temperatures_array * 2
print(temperatures_array_x2)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
----------------
[49.  50.2 52.6 54.  51.6]


4) Quelle différence observe-t-on ?

Sur la liste python lorsqu'on effectue une multiplication, les elements de la liste se duplique et quand on fait une multiplication sur le tableau numpy on obtient une multiplication element par element

Partie 2 – Création des données

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [6]:
#  Tableau de 10 capteurs, initialement à zéro
temperatures_capteurs = np.zeros(10)
print(temperatures_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Créer un tableau contenant 10 valeurs égales à 1.

In [7]:
# Tableau de 10 valeurs égales à 1
temperatures_uns = np.ones(10)
print(temperatures_uns)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Créer un tableau de 10 valeurs initialisées à 25.

In [8]:
# Tableau de 10 valeurs initialisées à 25
temperatures_25 = np.full(10, 25)
print(temperatures_25)

[25 25 25 25 25 25 25 25 25 25]


4) Créer une matrice identité de taille 5 × 5.

In [9]:
#  Matrice identité 5x5
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [10]:
# Les 24 heures de la journée (0 à 23)
heures = np.arange(24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [11]:
# 10 valeurs régulièrement réparties entre 20°C et 30°C
temperatures_reparties = np.linspace(20, 30, 10)
print(temperatures_reparties)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [12]:
# 100 mesures aléatoires de température, reproductibles
np.random.seed(42)
temperatures_100 = np.random.uniform(20, 30, 100)
print(temperatures_100)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30

# Partie 3 – Exploration des tableaux

1) Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [13]:
# 24 températures d'une journée (aléatoire)
np.random.seed(42)
temperatures_jour = np.random.uniform(20, 30, 24)
print(temperatures_jour)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]


2) Déterminer les propriétés suivantes du tableau
    a) nombre de dimensions 
    b) nombre de valeurs 
    c) type des données 
    d) forme du tableau

In [14]:
# 2) Propriétés du tableau
print("a) Nombre de dimensions :", temperatures_jour.ndim)
print("b) Nombre de valeurs :", temperatures_jour.size)
print("c) Type des données :", temperatures_jour.dtype)
print("d) Forme du tableau :", temperatures_jour.shape)

a) Nombre de dimensions : 1
b) Nombre de valeurs : 24
c) Type des données : float64
d) Forme du tableau : (24,)


# Partie 4 – Indexation et slicing

Considérant le tableau représentant les 24 températures d'une journée, afficher :


In [15]:
# 1) La première mesure
print(temperatures_jour[0])

23.745401188473625


In [16]:
# 2) La dernière mesure
print(temperatures_jour[-1])

23.663618432936918


In [17]:
# 3) La température de 8h
print(temperatures_jour[8])

26.011150117432088


In [18]:
# 4) Les températures de 8h à 12h
print(temperatures_jour[8:13])

[26.01115012 27.08072578 20.20584494 29.69909852 28.32442641]


In [19]:
# 5) Les températures des 6 premières heures
print(temperatures_jour[:6])

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452 ]


In [20]:
# 6) Les températures des heures paires
print(temperatures_jour[::2])

[23.74540119 27.31993942 21.5601864  20.58083612 26.01115012 20.20584494
 28.32442641 21.81824967 23.04242243 24.31945019 26.11852895 22.92144649]


# Partie 5 – Filtrage booléen
Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les
situations inhabituelles.

In [21]:
# 1) Températures supérieures à 30°C
print(temperatures_jour[temperatures_jour > 30])

[]


In [22]:
# 2) Températures normales (entre 20°C et 30°C)
print(temperatures_jour[(temperatures_jour >= 20) & (temperatures_jour <= 30)])

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]


In [23]:
# 3) Tableau booléen des anomalies (> 35°C)
anomalies = temperatures_jour > 35
print(anomalies)

[False False False False False False False False False False False False
 False False False False False False False False False False False False]


In [24]:
# 4) Nombre de températures anormales
nombre_anomalies = np.sum(anomalies)
print(nombre_anomalies)

0


# Partie 6 – Manipulation des dimensions
On suppose qu’on a 5 capteurs.

In [25]:
# 1) Matrice des températures : 5 capteurs x 24 heures
np.random.seed(42)
temperatures_capteurs = np.random.uniform(20, 30, (5, 24))
print(temperatures_capteurs)

[[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
  20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
  28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
  24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]
 [24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
  26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
  23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
  20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021]
 [25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
  25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
  23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
  21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682]
 [20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
  23.58465729 21.1586906  28.63103426 

In [ ]:
# 2) Transformation en tableau unidimensionnel

# flatten() crée une copie indépendante en 1D

temperatures_1d = temperatures_capteurs.flatten()
print(temperatures_1d)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30

In [31]:
# 3) Transposée de la matrice
temperatures_transposee = temperatures_capteurs.T
print(temperatures_transposee)
print("---------")
print(temperatures_capteurs.shape)
print(temperatures_transposee.shape)

[[23.74540119 24.56069984 25.46710279 20.05522117 25.22732829]
 [29.50714306 27.85175961 21.84854456 28.15461428 24.27541018]
 [27.31993942 21.99673782 29.69584628 27.06857344 20.25419127]
 [25.98658484 25.14234438 27.75132823 27.29007168 21.07891427]
 [21.5601864  25.92414569 29.39498942 27.71270347 20.31429186]
 [21.5599452  20.46450413 28.9482735  20.74044652 26.36410411]
 [20.58083612 26.07544852 25.97899979 23.58465729 23.14355981]
 [28.66176146 21.70524124 29.21874235 21.1586906  25.08570691]
 [26.01115012 20.65051593 20.88492502 28.63103426 29.07566474]
 [27.08072578 29.48885537 21.95982862 26.23298127 22.49292229]
 [20.20584494 29.65632033 20.45227289 23.30898025 24.10382923]
 [29.69909852 28.08397348 23.25330331 20.6355835  27.55551139]
 [28.32442641 23.04613769 23.8867729  23.10982322 22.28798165]
 [22.12339111 20.97672114 22.71349032 23.25183322 20.7697991 ]
 [21.81824967 26.84233027 28.28737509 27.29606178 22.89751453]
 [21.8340451  24.40152494 23.56753327 26.37557471 21.61

In [32]:
# 4) Toutes les mesures du capteur 1
print(temperatures_capteurs[0])

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]


In [33]:
# 5) Toutes les mesures du capteur 5
print(temperatures_capteurs[4])

[25.22732829 24.27541018 20.25419127 21.07891427 20.31429186 26.36410411
 23.14355981 25.08570691 29.07566474 22.49292229 24.10382923 27.55551139
 22.28798165 20.7697991  22.89751453 21.61221287 29.29697652 28.0812038
 26.33403757 28.7146059  28.03672077 21.86570059 28.92558998 25.39342242]


In [34]:
# 6) Mesures de tous les capteurs à 10h
print(temperatures_capteurs[:, 10])

[20.20584494 29.65632033 20.45227289 23.30898025 24.10382923]


In [35]:
# 7) Mesures des capteurs 2 à 4 entre 8h et 12h
print(temperatures_capteurs[1:4, 8:13])

[[20.65051593 29.48885537 29.65632033 28.08397348 23.04613769]
 [20.88492502 21.95982862 20.45227289 23.25330331 23.8867729 ]
 [28.63103426 26.23298127 23.30898025 20.6355835  23.10982322]]


# Partie 7 – Concaténation

On suppose qu’on a un 2nd bâtiment avec 3 capteurs.

In [36]:
# 1) Matrice des températures du 2nd bâtiment : 3 capteurs x 24 heures
np.random.seed(42)
temperatures_batiment2 = np.random.uniform(20, 30, (3, 24))
print(temperatures_batiment2)

[[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
  20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
  28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
  24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]
 [24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
  26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
  23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
  20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021]
 [25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
  25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
  23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
  21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682]]


In [37]:
# 2) Fusion des 8 capteurs 

# Méthode 1 : np.concatenate avec axis=0
# axis=0 signifie qu'on empile le long des lignes (donc on ajoute des capteurs

temperatures_8_capteurs_v1 = np.concatenate((temperatures_capteurs, temperatures_batiment2), axis=0)
print(temperatures_8_capteurs_v1)

[[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
  20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
  28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
  24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]
 [24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
  26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
  23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
  20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021]
 [25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
  25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
  23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
  21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682]
 [20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
  23.58465729 21.1586906  28.63103426 

# Partie 8 : Calcul scientifique
Considérons le tableau représentant les 24 températures du 1er bâtiment.

1) Pour les températures, calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l'écart-type

In [38]:
# 1) Statistiques descriptives sur temperatures_jour
minimum = np.min(temperatures_jour)
maximum = np.max(temperatures_jour)
somme = np.sum(temperatures_jour)
moyenne = np.mean(temperatures_jour)
mediane = np.median(temperatures_jour)
variance = np.var(temperatures_jour)
ecart_type = np.std(temperatures_jour)

print("Minimum :", minimum)
print("Maximum :", maximum)
print("Somme :", somme)
print("Moyenne :", moyenne)
print("Médiane :", mediane)
print("Variance :", variance)
print("Écart-type :", ecart_type)

Minimum : 20.205844942958024
Maximum : 29.699098521619945
Somme : 585.6389901515904
Moyenne : 24.4016245896496
Médiane : 23.70450981070527
Variance : 8.133920360198433
Écart-type : 2.8520028681960388


In [39]:
# 2) Standardisation
temperatures_standardisees = (temperatures_jour - moyenne) / ecart_type
print(temperatures_standardisees)

# Vérification
print("Moyenne après standardisation :", np.mean(temperatures_standardisees))
print("Écart-type après standardisation :", np.std(temperatures_standardisees))

[-0.23009213  1.79015194  1.02325101  0.55573585 -0.9962957  -0.99638027
 -1.33968605  1.49373513  0.5643492   0.93937535 -1.4711695   1.85745743
  1.37545507 -0.79881879 -0.90581077 -0.90027241 -0.47657812  0.29661251
 -0.02881288 -0.52220606  0.60199952 -1.05423666 -0.51899601 -0.25876768]
Moyenne après standardisation : 7.401486830834377e-17
Écart-type après standardisation : 1.0


In [40]:
# 3) Normalisation Min-Max
temperatures_normalisees = (temperatures_jour - minimum) / (maximum - minimum)
print(temperatures_normalisees)

# Vérification
print("Minimum après normalisation :", np.min(temperatures_normalisees))
print("Maximum après normalisation :", np.max(temperatures_normalisees))

[0.37284965 0.9797798  0.74938422 0.60893137 0.14266357 0.14263816
 0.03950081 0.89072903 0.61151903 0.72418595 0.         1.
 0.85519484 0.20199041 0.16984743 0.17151129 0.2987993  0.53108445
 0.4333188  0.28509156 0.62283009 0.12525671 0.28605594 0.36423482]
Minimum après normalisation : 0.0
Maximum après normalisation : 1.0


In [41]:
# 4) Conversion en Fahrenheit
# Le Fahrenheit est une échelle de température où l'eau gèle à 32°F et bout à 212°F
# (contre 0°C et 100°C en Celsius). La formule de conversion est F = C * 9/5 + 32
temperatures_fahrenheit = temperatures_jour * 9/5 + 32
print(temperatures_fahrenheit)

[74.74172214 85.11285752 81.17589095 78.77585272 70.80833553 70.80790137
 69.04550502 83.59117062 78.82007021 80.7453064  68.3705209  85.45837734
 82.98396753 71.82210399 71.27284941 71.30128118 73.47636037 77.44561577
 75.77501034 73.24212452 79.01335211 70.51088949 73.25860367 74.59451318]
